language: java

env:
  - MAVEN_VERSION=3.3.9
  - MAVEN_VERSION=3.5.4
  - MAVEN_VERSION=3.6.1

jdk: oraclejdk8

install:
  - "mvn --show-version -Psonatype install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
before_script:
    # reset correct branch information
    - "./travis-set-branch.sh"
script:
    - "mvn --show-version -Psonatype -Prun-its clean install"

cache:
  directories:
    - $HOME/.m2

branches:
    except:
        - gh-pages

notifications:
  email:
    - matthieu@brouillard.fr
